#!/usr/bin/env python

# Copyright (C) 2012 Nick Thuesen
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.

from optparse import OptionParser
import shlex
import subprocess
import sys


class RabbitCmdWrapper(object):
    """So basically this just runs rabbitmqctl commands and returns parsed output.
       Typically this means you need root privs for this to work.

       Made this it's own class so it could be used in other monitoring tools
       if desired."""

    @classmethod
    def list_connections(cls, vhost=None):
        args = shlex.split("sudo rabbitmqctl list_connections")
        if vhost:
            args.extend(["-p", vhost])
        cmd_result = subprocess.check_output(args).strip()
        results = cls._parse_list_results(cmd_result)
        return results

    @classmethod
    def list_queues(cls, vhost=None):
        args = shlex.split('sudo rabbitmqctl list_queues')
        if vhost:
            args.extend(["-p", vhost])
        cmd_result = subprocess.check_output(args).strip()
        results = cls._parse_list_results(cmd_result)
        return results

    @classmethod
    def _parse_list_results(cls, result_string):
        results = result_string.strip().split('\n')
        #remove text fluff
        results.remove(results[-1])
        results.remove(results[0])
        return_data = []
        for row in results:
            return_data.append(row.split('\t'))
        return return_data




def check_connection_count(critical=0, warning=0, vhost=None):
    """Checks to make sure the numbers of connections are within parameters."""
    try:
        count = len(RabbitCmdWrapper.list_connections())
        if count >= critical:
            print "CRITICAL - Connection Count %d" % count
            sys.exit(2)
        elif count >= warning:
            print "WARNING - Connection Count %d" % count
            sys.exit(1)
        else:
            print "OK - Connection Count %d" % count
    except Exception, err:
        print "CRITICAL - %s" % err

def check_queues_count(critical=1000, warning=1000, vhost=None):
    """
    A blanket check to make sure all queues are within count parameters.
    TODO: Possibly break this out so test can be done on individual queues.
    """
    try:
        results = RabbitCmdWrapper.list_queues()
        for queue in results:
            if queue[1] >= critical:
                print "CRITICAL - Queue %s count %s" % (queue[0], queue[1])
                return
            elif queue[1] >= warning:
                print "WARNING - Queue %s count %s" % (queue[0], queue[1])
                return
        print "OK - Queues %s" % str([ "%s : %s" % (q[0],q[1]) for q in results])
    except Exception, err:
        print "CRITICAL - %s" % err



USAGE = """Usage: ./check_rabbitmq -a [action] -c [critical] -w [warning] -p [vhost]
           Actions:
           - connection_count
             checks the number of connection in rabbitmq's list_connections
           - queues_count
             checks the count in each of the queues in rabbitmq's list_queues"""

if __name__ == "__main__":
    parser = OptionParser(USAGE)
    parser.add_option("-a", "--action", dest="action",
            help="Action to Check")
    parser.add_option("-C", "--critical", dest="critical",
            help="Critical Threshold")
    parser.add_option("-W", "--warning", dest="warning",
            help="Warning Threshold")
    parser.add_option("-p", "--vhostpath", dest="vhost",
            help="Virtual Host Path")
    (options, args) = parser.parse_args()

    if options.action == "connection_count":
        check_connection_count(options.critical, options.warning, options.vhost)
    elif options.action == "queues_count":
        check_queues_count(options.critical, options.warning, options.vhost)
    else:
        print "Invalid action: %s" % options.action
        print USAGE
